version: "3.8"

services:
  intranet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intranet-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
